### ISSUE TITLE
attempt to make this on an ARMv8 server fails

### ISSUE THREAD

**Issue by vielmetti** [fdebonneval/mobydig#2]
I'm trying to use this to build on an ARMv8 server rather than a Mac. So far I have gotten this far:

```
Step 1 : FROM ubuntu:16.04
 ---> 104bec311bcd
Step 2 : MAINTAINER Foucault de Bonneval <foucault(at)commit.ninja>
 ---> Using cache
 ---> b3723bf29764
Step 3 : LABEL RUN "docker run -i -t --privileged -v /var/run/docker.sock:/host/var/run/docker.sock -v /dev:/host/dev -v /proc:/host/proc:ro -v /lib/modules:/host/lib/modules:ro -v /usr:/host/usr:ro --name NAME IMAGE"
 ---> Using cache
 ---> 5f6f70e5e8e7
Step 4 : ARG application_version
 ---> Using cache
 ---> 31e8b98a8ff3
Step 5 : COPY resources /tmp/resources
 ---> Using cache
 ---> 47e573de59e7
Step 6 : ENV SYSDIG_HOST_ROOT /host
 ---> Using cache
 ---> 2372651e8eed
Step 7 : RUN /tmp/resources/build && rm -rf /tmp/resources
 ---> Running in ed09e5115963
write pipe: bad file descriptor
The command '/bin/sh -c /tmp/resources/build && rm -rf /tmp/resources' returned a non-zero code: 1
Makefile:25: recipe for target 'build' failed
make: *** [build] Error 1
```

This seems pretty fundamental but I don't know which line in the build script is giving me the error. Any debug thoughts welcomed.

**Comment by fdebonneval** [comment]
Hi Edward,

I'am sooo sorry for the delay. It seems that I do not have email notifications for the issues / PR opened on this project. I'am gonna fix that straight away.

If the problem is still one, you could try digging a bit with proceeding the next steps : 
* open Dockerfile and comment last two lines 'RUN' and 'ENTRYPOINT'
* launch a build using the `$ make build` command

You will now have a context you can debug easily with getting into the container using the command `$ docker run --rm -it mobydig:dev bash`
You can the now run the build script manually : `$ /tmp/resources/build` and please tell me what happened 
The build script runs with +xe so it should be more verbose.
Anyway, please try that.
Thanks,
Foucault

**Comment by fdebonneval** [comment]
Hi @vielmetti 

Did you, by any chance, had time to take a look at my answer ?

Thanks,
Foucault

**Comment by vielmetti** [comment]
Thanks @fdebonneval ! I did see this and will hope to circle back to it in the next couple of days - thanks for the reminder!
